
test <- read.csv("D:/Metatable/R_WebSite1/test.csv")
aa <- as.data.frame(test)
bb <-as.matrix(aa)
write(t(bb), file = "D:/Metatable/R_WebSite1/result/data.csv",ncolumns=ncol(bb), sep = ",")
require('ggplot2')
library('ggplot2')
png("D:/Metatable/R_WebSite1/result/DataPic.png")
ggplot(aa,aes(x=TEMP,y=WSP))+geom_point()
dev.off()